export * from './clientes.model';
export * from './tipo-prestamos.model';
export * from './prestamos.model';
export * from './pagos.model';
export * from './cuotas.model';
export * from './roles.model';
export * from './usuario.model';
export * from './credenciales.model';
export * from './codigo-verificacion.model';
