export * from './Clientes.model';
export * from './tipo-prestamos.model';
export * from './prestamos.model';
export * from './Pagos.model';
export * from './Cuotas.model';
export * from './roles.model';
export * from './usuario.model';
export * from './credenciales.model';
export * from './codigo-verificacion.model';
