export * from './Clientes.repository';
export * from './codigo-verificacion.repository';
export * from './credenciales.repository';
export * from './Cuotas.repository';
export * from './Pagos.repository';
export * from './Prestamos.repository';
export * from './roles.repository';
export * from './usuario.repository';
export * from './TipoPrestamos.repository';