export * from './clientes.repository';
export * from './codigo-verificacion.repository';
export * from './credenciales.repository';
export * from './cuotas.repository';
export * from './pagos.repository';
export * from './prestamos.repository';
export * from './roles.repository';
export * from './usuario.repository';
export * from './tipo-prestamos.repository';